name: flake update job
run-name: ${{ github.actor }} updates the flake
on: 
  schedule:
    - cron: 0 0 */3 * *
  workflow_dispatch:
jobs:
  flakeUpdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix flake update
