name: flake update job
run-name: ${{ github.actor }} updates the flake
on: 
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:
jobs:
  flakeUpdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - name: Update Nix Flake Lock
        uses: DeterminateSystems/update-flake-lock@v24

